import os
from pathlib import Path

# Core paths
ROOT_DIR = Path(".")
DATA_DIR = ROOT_DIR / "data"
PIECES_DIR = DATA_DIR / "pieces"
RESULTS_DIR = ROOT_DIR / "results"

# Agent artifacts
RESEARCH_LOG_PATH = RESULTS_DIR / "research_log.md"
BEST_RESULT_PATH = RESULTS_DIR / "best_result.json"
KNOWN_FACTS_PATH = RESULTS_DIR / "known_facts.json"
EXPERIMENTS_JSONL_PATH = RESULTS_DIR / "experiments.jsonl"
ATTEMPT_SUMMARY_TSV_PATH = RESULTS_DIR / "attempt_summary.tsv"
RESEARCH_SYNTHESIS_PATH = RESULTS_DIR / "research_synthesis.md"
RESULTS_TSV_PATH = RESULTS_DIR / "results.tsv"
PROBLEM_PATH = ROOT_DIR / "problem.md"
SOLUTION_OUTPUT_PATH = RESULTS_DIR / "solution_output.txt"

# Model settings
NIM_BASE_URL = "https://api.cerebras.ai/v1"
NIM_API_KEY = os.getenv("CEREBRAS_API_KEY")
MODEL = "zai-glm-4.7"
MODEL_MAX_OUTPUT_TOKENS = 16384
EMPTY_MESSAGE_CONTENT_RETRIES = 2

# Agent runtime settings
SOLUTION_TIMEOUT_SECS = 300
MAX_ITERATIONS = 1000
SCRIPT_COMPILE_REPAIR_ATTEMPTS = 2
CONTEXT_EXPERIMENT_LIMIT = 18
SYNTHESIS_CONTEXT_TAIL = 3200
SYNTHESIS_PRIOR_TAIL = 7000
SYNTHESIS_MAX_OUTPUT_TOKENS = 4096
PRIOR_INVESTIGATE_SCRIPT_CHARS = 9000
PRIOR_SOLVE_ATTEMPT_SCRIPT_CHARS = 7500
PRIOR_BEST_SOLVER_SCRIPT_CHARS = 5500

# Memory settings
MAX_MEMORY_ENTRY_CHARS = 200
MAX_MEMORY_LIST_ITEMS = 80
MEMORY_UPDATE_MAX_TOKENS = 800
MEMORY_EXTRACT_MAX_PER_LIST = 5
MEMORY_SIMILARITY_DEDUPE = 0.78
MEMORY_SHORT_LEN = 28
